version: '3.7'
services:
  nginx-webui:
    build: .
    container_name: nginx-webui
    environment:
      - TZ=Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
  # deploy:
    # resources:
      # limits:
        # cpus: '0.5'
        # memory: 1024M
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - nginx-webui-data:/data
      - nginx-webui-cert:/cert
      - nginx-webui-session:/session
      - nginx-webui-log:/var/log/nginx
      - ./admin:/admin

volumes:
  nginx-webui-data:
  nginx-webui-cert:
  nginx-webui-session:
  nginx-webui-log:
