version: '3.7'
services:
  nginx-ui:
    build: .
    container_name: nginx-ui
    environment:
      - TZ=Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
  # deploy:
    # resources:
      # limits:
        # cpus: '0.5'
        # memory: 1024M
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./admin:/admin
