name: build-docker

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for non-ASCII characters (excluding emoji)
        run: |
          set -e

          if grep -rInP '[^\x00-\x7F]' . \
            --exclude-dir=.git \
            --exclude-dir=node_modules \
            --exclude-dir=dist \
            --binary-files=without-match; then
              echo "Non-ASCII character detected. abort."
              exit 1
          else
              echo "All good."
          fi

      - name: Extract version and set it to TAG env var
        run: echo "TAG=$(jq -r '.version' admin/package.json)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            lancard/nginx-webui:latest
            lancard/nginx-webui:${{ env.TAG }}            
