name: build-module-version-up

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install npm-check-updates
        run: npm install -g npm-check-updates

      - name: version up
        run: |
          cd admin
          npm version patch
          ncu -ws -u
          npm install

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com      
          git add .
          git commit -am "module version up"
          git push