name: build-module-version-up

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: version up
        run: |
          cd admin
          npm version patch

      - name: npm update
        run: |
          cd admin
          npm update
          npm update --save

      # ignore bower due to .gitignore file
      # - name: bower update
      #   run: |
      #     npm install -g bower
      #     cd admin/static
      #     bower install jquery moment fontawesome --save

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com      
          git add .
          git commit -am "module version up"
          git push